### ISSUE TITLE
Add some additional monitoring to ensure autoclassification is behaving correctly

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#739]
E.g. if a push is backed out and we have all failures on the push and its children classified as intermittent, then there's something wrong and we should manually check the autoclassifications.

- [x] Warn about pushes that are backed-out and where all failures on the push itself and its children are marked as intermittent (#761)
- [x] Warn if there is a classification that references a revision that does not exist (#779)
- [x] Warn if there is a group that is failing in a set of pushes and marked sometimes as intermittent and sometimes as fixed by commit or sometimes as fixed by a backout and sometimes fixed by another backout (#781)
- [x]  Build a graph that shows the number of failures classified as intermittent (divided by number of pushes and by number of tasks) over time: [Intermittent failures/100 adjacent pushes](https://sql.telemetry.mozilla.org/queries/86531#214296)

- [x]  Build a graph of average number of intermittents per push or per 100 jobs: see above

- [x]  Show number of retriggers and number of backfills we perform (divided by number of pushes and by number of tasks) over time: [overall count of additional tasks](https://sql.telemetry.mozilla.org/queries/86793#215014) - includes those requested by performance sheriffs
- [x] Warn if there is a failure that starts happening on a push that comes before the push that is backed-out and which is marked as "fixed by commit" of the backout of the second push (https://github.com/mozilla/mozci/blob/6cf1980876d9c48562e983728c8f253ca9cb7073/mozci/push.py#L564) (#783)

**Comment by marco-c** [comment]
@ahal @Archaeopteryx @jmaher any other idea for consistency checks that we could implement for classifications?

**Comment by jmaher** [comment]
in a future world where everything is autoclassified, then backouts are the only signal I can think of.  Possibly we can have some heuristics about total number of intermittents seen on a push or per 100 jobs- then we can determine if things are getting too frequent.  i.e. if we have 10 failures/100 test jobs on average, if we have >12 failures for 100 test jobs then a human should take a look.

**Comment by marco-c** [comment]
Good idea, we could at least have some graphs sent weekly to see these numbers and how they evolve.

**Comment by marco-c** [comment]
As part of this, we should also add the number of retriggers and number of backfills we perform (normalized by number of pushes).

**Comment by marco-c** [comment]
To summarize, the monitoring hook should
- list pushes that are backed-out and where all failures on the push itself and its children are marked as intermittent;
- build a graph that shows the number of failures classified as intermittent (divided by number of pushes and by number of tasks) over time;
- show number of retriggers and number of backfills we perform (divided by number of pushes and by number of tasks) over time.

These can all be implemented in separate PRs of course.

**Comment by La0** [comment]
> build a graph that shows the number of failures classified as intermittent (divided by number of pushes and by number of tasks) over time;

Would the rendered graph be stored as an image, as a Taskcluster artifact on the monitoring task ? If set to public, its url could be used in the email message being sent.

**Comment by La0** [comment]
> over time 

Do you mean we need data persistence somewhere ? The monitoring hook only supports a given date range, so it would only process the pushes found in the range.

Currently, it only looks over 1 day of push.

**Comment by marco-c** [comment]
> Would the rendered graph be stored as an image, as a Taskcluster artifact on the monitoring task ? If set to public, its url could be used in the email message being sent.

Yes, sounds like the easiest way to implement it!

**Comment by marco-c** [comment]
> Do you mean we need data persistence somewhere ? The monitoring hook only supports a given date range, so it would only process the pushes found in the range.
> 
> Currently, it only looks over 1 day of push.

For these numbers, it could look at a larger number of days (so we don't need persistence). For number of failures classified as intermittent, it could get this data from Treeherder somehow.
If getting a larger number of days is expensive, we could make the monitoring hook generate an artifact with the numbers, and the next run will get the previous file and update it.

**Comment by La0** [comment]
So we would run a new classification process (using `classify-eval`) over a larger number of days (say a month), on a different periodicity (once every week ?).

This task would then generate a graph using all the data it generated, through a new CLI option named `--build-graph`

In the end, the mozci command would be:

```
mozci push classify-eval --from-date="1 month ago" --send-email --recalculate --environment=testing --build-graph
```

The `build-graph` option would generate a graph locally, store it as an artifact and embed this image through a link towrads the artifact in the sent email.

Does this monitoring tool replace the existing one or is it a new one in parallel of the existing one ?

@marco-c WDYT ?

**Comment by marco-c** [comment]
That sounds good to me, but I'm not sure about the performance. Is it going to be super slow? Or is it going to be fast because we have almost everything already cached?

> Does this monitoring tool replace the existing one or is it a new one in parallel of the existing one ?

I'd say in parallel, as the other one can quickly warn us about things that we can quickly fix.

**Comment by La0** [comment]
A few more questions @marco-c :
- Is it OK if @EvaBardou produces one MR per bullet point matching your description ?
- Do you want to toggle these extended features through CLI options (say `--extended-warnings` or should they always be calculated, even in the current hook).

**Comment by marco-c** [comment]
>     * Is it OK if @EvaBardou produces one MR per bullet point matching your description ?

Yes, that'd be preferable.

>     * Do you want to toggle these extended features through CLI options (say `--extended-warnings` or should they always be calculated, even in the current hook).

No I think we can always calculate them.

**Comment by marco-c** [comment]
For `Warn if there is a group that is failing in a set of pushes and marked sometimes as intermittent and sometimes as fixed by commit or sometimes as fixed by a backout and sometimes fixed by another backout`, we can rely on _iterate_failures, just like for #761.
We basically need to check that classified_as_cause[group] for each group is consistently all True, or all False, or all None.

**Comment by marco-c** [comment]
Regarding the remaining things to do, building graphs, we could build queries in Redash. It should be much easier.

**Comment by Archaeopteryx** [comment]
* [x]  Build a graph that shows the number of failures classified as intermittent (divided by number of pushes and by number of tasks) over time: [Intermittent failures/100 adjacent pushes](https://sql.telemetry.mozilla.org/queries/86531#214296)

* [x]  Build a graph of average number of intermittents per push or per 100 jobs: see above

* [x]  Show number of retriggers and number of backfills we perform (divided by number of pushes and by number of tasks) over time: [overall count of additional tasks](https://sql.telemetry.mozilla.org/queries/86793#215014) - includes those requested by performance sheriffs

**Comment by marco-c** [comment]
Let's call this fixed, we'll add more over time for sure, but we have everything we wanted.
